Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "ansible/playbook.yml"
  end
  config.vm.synced_folder "../myproject/", "/opt/absolute/myproject"
  config.vm.network :forwarded_port, guest: 5000, host: 12313
  config.vm.provision :shell, path: "../myproject/startup.sh"
end
