---
- hosts: all
  become: yes
  roles:
    - nginx
  tasks:
    - include: tasks/flask.yml
    - name: make sure path exists to install flask application
      file: path=/opt/absolute state=directory
    - name: Deploy Flask application
      synchronize: src=../../myproject dest=/opt/absolute

- hosts: all
  tasks:
    - include: tasks/startup.yml
